name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-fedora:
    runs-on: ubuntu-24.04
    container:
      image: quay.io/fedora/fedora:41
      options: "--privileged --pid=host -v /var/tmp:/var/tmp -v /:/run/host"

    steps:
    - run: dnf -y install cargo clippy composefs-devel e2fsprogs rustfmt
    - name: Enable fs-verity on /
      run: tune2fs -O verity $(findmnt -vno SOURCE /run/host)
    - uses: actions/checkout@v4
    - run: cargo build --verbose
    - run: cargo fmt --check
    - run: cargo clippy -- -Dwarnings
    - run: env CFS_TEST_TMPDIR=/run/host/var/tmp cargo test --verbose
